### PR TITLE
Devserver

### PR DESCRIPTION
**Pull request by mkiwala**

### CODE REVIEW

**Comment by davidlmorton** [comment]
We have to look at coverage drops again.

**Comment by davidlmorton** [comment]
So we have two problems:
1) run_tests isn't exiting non-zero when a test fails.
2) It takes a long time now to spin up a devserver for the first time, and we don't wait long enough:

22:38:58 petri.1        | dev-noenv installdeps: -r/home/vagrant/ptero/services/petri/requirements.txt, -r/home/vagrant/ptero/services/petri/test-requiremen
ts.txt
22:39:45 petri.1        | dev-noenv develop-inst: /home/vagrant/ptero/services/petri

That's nearly a minute.  The time is a lot longer than it used to be because it has to create a new virtualenv from scratch, and it didn't used to.  I see at least two options...

a) we invent some way of knowing that the services are all up before we start.
b) we implement retrying of failed connections (we've talked about it but apparently we haven't done it.)

I think that (b) is better suited for the real-world so we should probably do that.

**Comment by mkiwala** [comment]
+1

**Comment by davidlmorton** [comment]
I've also turned off coverage putting pass/fail statuses on the PRs, it will still add the comments, but not add the fail and put the red x there.

**Pull request merged**
