### PR TITLE
Url parse

### LINKED ISSUE #247: POSTing to /v1/workflows should never result in 404 Not Found
The 404 status code is reserved for when the server cannot find a resource matching the requested URL.  In the v1 api for ptero-workflow, `/v1/workflows` is defined, so a 404 should never result from making a request to this url.

### PR DESCRIPTION
**Pull request by mkiwala**
Fixes #247 and adds logging to help understand failing model tests with spawned workflows.

This PR is missing a negative test to confirm that InvalidExecutionUrlError is raised when we expect it to be raised.

Also, the urls.py could be improved by having the 'format' and 'parser' strings auto-generated from the 'url' string (eg, '/executions/<int:execution_id>').

### CODE REVIEW

**Comment by davidlmorton** [comment]
It should be easy to add tests for url_parse directly, I think we should add those before we merge this PR.

**Comment by mkiwala** [comment]
I added a test for url_parse.  Maybe we can get this into staging this weekend and run the model tests.

**Comment by davidlmorton** [comment]
I leave that up to you.  I ran the updated (more strict) tests against production and confirmed that the bug that is preventing spawned workflows isn't in production.  I'm not sure it is important enough that it cannot wait until Monday.

**Comment by mkiwala** [comment]
Tests are currently failing on this PR.  I suspected whatever the cause of these failures is, it is not the code introduced in this PR.  To demonstrate that the failures are not due to code on this PR, I had travis-ci re-run a previously successful test on this PR (the test run associated with cd0fb89).

**Comment by davidlmorton** [comment]
It is interesting that they seem to be failing on anything needing the shell-command service, and that they were both working on the same test 'parallel_by_dag' when they timed out.  I'm not sure what's going on, but I was able pass tests after restarting the travis CI build on another open PR on this repo (PR #237  Travis CI build https://travis-ci.org/genome/ptero-workflow/builds/103694812).

**Comment by mkiwala** [comment]
Ok, it's better now.  I re-ran the latest test on the PR, and the problem went away.

Also, I had first noticed this problem in the development environment.  The problem is no longer occurring there either.

I think all of the comments on this PR have been addressed.

**Pull request merged**
